---
environment:
  # image: amlt-sing/acpt-1.13.1-py3.9-cuda11.7
  # image: amlt-sing/acpt-2.2.2-py3.10-cuda11.8
  # image: amlt-sing/acpt-2.3.1-py3.10-cuda11.8
  # image: amlt-sing/acpt-2.2.2-py3.10-cuda11.8
  # image: amlt-sing/acpt-2.2.2-py3.10-cuda12.1
  image: amlt-sing/acpt-torch2.7.0-py3.10-cuda12.6-ubuntu22.04
  # conda_yaml_file: $CONFIG_DIR/VidTok/environment.yaml
  # image: stillkeeptry/singularity_openmpi:deepspeed <-
  # image: azureml/minimal-ubuntu22.04-py39-cuda11.8-gpu-inference:latest
  # conda_yaml_file: $CONFIG_DIR/environment.yml
  setup:
  - . amlt_setup.sh

env_defaults:
  NODES: 1
  GPUS: 8
  # CPUS: 512
  MEM: 200
  # WANDB_MODE: offline
  # infinite band
  # NCCL_IB_DISABLE: 0
  # NCCL_IB_PCI_RELAXED_ORDERING: 1
  # NCCL_SOCKET_IFNAME: eth0
  # NCCL_NET_GDR_LEVEL: 5
  # NCCL_TOPO_FILE: /opt/microsoft/ndv4-topo.xml


target:
  service: sing
  # name: msroctovc
  # name: msrresrchvc
  name: palisades03
  # name: msroctobasicvc
  # name: msrresrchlab
  # name: msrresrchbasicvc
  # name: msroctobasicvc
  workspace_name: msra-sh-aml-ws

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR

storage:
  data:
    storage_account_name: caihuashan
    container_name: zehui
    # The datasets container will be mounted at this folder when run in Amulet.
    # The user code has to append a subfolder to this path to access the data.
    mount_dir: /mnt/data


# list of jobs to run
jobs:
- name: gfm_nt_pretrain_formal
  # sku: NC_A100_v4:${NODES}x${MEM}G${GPUS}
  sku: ${NODES}x${MEM}G${GPUS}
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
      WANDB_API_KEY: "$WANDB_API_KEY"
  command:
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && torchrun --nnodes=$NODES --nproc_per_node=$GPUS main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log_mi --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model nt
  # - /home/aiscuser/.local/bin/accelerate launch heart_finetune.py
  # - python heart_finetune.py
  # - cd sft_qwen && /home/aiscuser/.local/bin/accelerate launch --machine_rank=$$RANK --main_process_ip=$$MASTER_ADDR --main_process_port=$$MASTER_PORT --config_file config/ddp.yaml sft.py --output_path /mnt/data/ar_vid/ckpt
  process_count_per_node: 1

- name: gfm_dnabert2_formal
  # sku: NC_A100_v4:${NODES}x${MEM}G${GPUS}
  sku: ${NODES}x${MEM}G${GPUS}
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
      WANDB_API_KEY: "$WANDB_API_KEY"
  command:
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && torchrun --nnodes=$NODES --nproc_per_node=$GPUS main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log_mi --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  - python - <<<'import kipoiseq, sys; print("kipoiseq version:", getattr(kipoiseq, "__version__", "unknown"))'
  - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model dnabert2
  # - /home/aiscuser/.local/bin/accelerate launch heart_finetune.py
  # - python heart_finetune.py
  # - cd sft_qwen && /home/aiscuser/.local/bin/accelerate launch --machine_rank=$$RANK --main_process_ip=$$MASTER_ADDR --main_process_port=$$MASTER_PORT --config_file config/ddp.yaml sft.py --output_path /mnt/data/ar_vid/ckpt
  process_count_per_node: 1

- name: gfm_dnabert2_formal_smart
  # sku: NC_A100_v4:${NODES}x${MEM}G${GPUS}
  sku: ${NODES}x${MEM}G${GPUS}
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
      WANDB_API_KEY: "$WANDB_API_KEY"
  command:
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && torchrun --nnodes=$NODES --nproc_per_node=$GPUS main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log_mi --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  - python - <<<'import kipoiseq, sys; print("kipoiseq version:", getattr(kipoiseq, "__version__", "unknown"))'
  - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model dnabert2
  # - /home/aiscuser/.local/bin/accelerate launch heart_finetune.py
  # - python heart_finetune.py
  # - cd sft_qwen && /home/aiscuser/.local/bin/accelerate launch --machine_rank=$$RANK --main_process_ip=$$MASTER_ADDR --main_process_port=$$MASTER_PORT --config_file config/ddp.yaml sft.py --output_path /mnt/data/ar_vid/ckpt
  process_count_per_node: 1

- name: omni_dna
  # sku: NC_A100_v4:${NODES}x${MEM}G${GPUS}
  tags: ["Project_Name:LongVideoGeneration"]
  sku: ${NODES}x${MEM}G${GPUS}
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
      WANDB_API_KEY: "$WANDB_API_KEY"
  command:
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && torchrun --nnodes=$NODES --nproc_per_node=$GPUS main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log_mi --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  - python - <<<'import kipoiseq, sys; print("kipoiseq version:", getattr(kipoiseq, "__version__", "unknown"))'
  # - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model nt
  - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model dnabert2
  # - python heart_finetune.py --model dnabert2
  # - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model hyenaDNA --decoder
  # - /home/aiscuser/.local/bin/accelerate launch heart_finetune.py
  # - python heart_finetune.py
  # - cd sft_qwen && /home/aiscuser/.local/bin/accelerate launch --machine_rank=$$RANK --main_process_ip=$$MASTER_ADDR --main_process_port=$$MASTER_PORT --config_file config/ddp.yaml sft.py --output_path /mnt/data/ar_vid/ckpt
  process_count_per_node: 1


- name: omni_dna_hyena_dna
  # sku: NC_A100_v4:${NODES}x${MEM}G${GPUS}
  tags: ["Project_Name:LongVideoGeneration"]
  sku: ${NODES}x${MEM}G${GPUS}
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
      WANDB_API_KEY: "$WANDB_API_KEY"
  command:
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && torchrun --nnodes=$NODES --nproc_per_node=$GPUS main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  # - cd VidTok && python main.py -b configs/vidtok_v1_1/cat_vidtok_fsq_causal_488_32768_v1_1.yaml --logdir /mnt/data/intern_vl_hunyuan/wandb_log_mi --wandb --wandb_entity zehui127-imperial-college-london --wandb_project catvidtok
  - python - <<<'import kipoiseq, sys; print("kipoiseq version:", getattr(kipoiseq, "__version__", "unknown"))'
  # - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model nt
  - /home/aiscuser/.local/bin/accelerate launch --config_file configs/ddp.yaml heart_finetune.py --model hyenaDNA --decoder
  process_count_per_node: 1
