digenic_hyena-tiny:
  class: OligogenicDataWrapper
  task: classification
  target: 
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2
  
regulatory_hyena-tiny:
  class: EnsemblRegulatoryDataWrapper
  task: classification
  target: 
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2
  
mave_score_hyena-tiny:
  class: MAVEDataWrapper
  task: regression
  target: score
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1
  
gwas_pval_hyena-tiny:
  class: GWASDataWrapper
  task: regression
  target: P-Value
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1
  
promoter_hyena-tiny:
  class: PromoterDataWrapper
  task: classification
  target: 
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2

clinvar_CLNSIG_hyena-tiny:
  class: ClinVarDataWrapper
  task: classification
  target: CLNSIG
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: hyenadna-tiny-1k
  output_size: 4

clinvar_CLNDN_hyena-tiny:
  class: ClinVarDataWrapper
  task: classification
  target: CLNDN
  model_initiator_name: hyenadna-tiny-1k
  output_size: 13209 # number of unique diseases in the dataset

geneko_hyena-tiny:
  class: GeneKoDataWrapper
  task: regression
  insert_Ns: False
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

eqtl_pval_hyena-tiny:
  class: eQTLDataWrapper
  task: regression
  target: p_val
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

eqtl_slope_hyena-tiny:
  class: eQTLDataWrapper
  task: regression
  target: slope
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

sqtl_pval_hyena-tiny:
  class: sQTLDataWrapper
  task: regression
  target: p_val
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

sqtl_slope_hyena-tiny:
  class: sQTLDataWrapper
  task: regression
  target: slope
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

sqlt_splice-change_hyena-tiny:
  class: sQTLDataWrapper
  task: regression
  target: splice_change
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2

cellpassport_hyena-tiny:
  class: CellPassportDataWrapper
  task: classification
  Seq_length: 2048
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2
