oligogenic_hyena-tiny:
  class: OligogenicDataWrapper
  task: classification
  Seq_length: 1024
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2

mave_score_hyena-tiny:
  class: MAVEDataWrapper
  task: regression
  target: score
  Seq_length: 2048
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

gwas_pval_hyena-tiny:
  class: GWASDataWrapper
  task: regression
  target: P-Value
  Seq_length: 2048
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

clinvar_CLNSIG_hyena-tiny:
  class: ClinVarDataWrapper
  task: classification
  target: CLNSIG
  Seq_length: 1024
  pca_components: 16
  final_pca_components: 1
  model_initiator_name: hyenadna-tiny-1k
  num_records: 40000
  all_records: False
  output_size: 4

real_clinvar_hyena-tiny:
  class: RealClinVar
  task: classification
  target: CLASS
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: hyenadna-tiny-1k
  output_size: 4

real_clinvar_random:
  class: RealClinVar
  task: classification
  target: CLASS
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: hyenadna-tiny-1k
  output_size: 4

real_clinvar_dnabert2:
  class: RealClinVar
  task: classification
  target: CLASS
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: dnabert2
  output_size: 4

real_clinvar_nt:
  class: RealClinVar
  task: classification
  target: CLASS
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: nt_transformer_human_ref
  output_size: 4

real_clinvar_ntv2:
  class: RealClinVar
  task: classification
  target: CLASS
  Seq_length: 1024
  pca_components: 16
  model_initiator_name: nt_transformer_v2_500m
  output_size: 4

clinvar_CLNDN_hyena-tiny:
  class: ClinVarDataWrapper
  task: classification
  target: CLNDN
  model_initiator_name: hyenadna-tiny-1k
  output_size: 13209 # number of unique diseases in the dataset

geneko_hyena-tiny:
  class: GeneKoDataWrapper
  task: regression
  insert_Ns: False
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

eqtl_pval_hyena-tiny:
  class: eQTLDataWrapper
  task: regression
  target: p_val
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

eqtl_slope_hyena-tiny:
  class: eQTLDataWrapper
  task: regression
  target: slope
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

sqtl_pval_hyena-tiny:
  class: sQTLDataWrapper
  task: regression
  target: p_val
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

sqtl_slope_hyena-tiny:
  class: sQTLDataWrapper
  task: regression
  target: slope
  model_initiator_name: hyenadna-tiny-1k
  output_size: 1

sqlt_splice-change_hyena-tiny:
  class: sQTLDataWrapper
  task: regression
  target: splice_change
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2

cellpassport_hyena-tiny:
  class: CellPassportDataWrapper
  task: classification
  Seq_length: 2048
  pca_components: 16
  model_initiator_name: hyenadna-tiny-1k
  output_size: 2
  num_records: 100
  all_records: False
