clinvar_CLNSIG_hyena-tiny:
  class: ClinVarDataWrapper
  task: classification
  target: CLNSIG
  Seq_length: 1024
  pca_components: 16
  final_pca_components: 1
  model_initiator_name: hyenadna-tiny-1k
  num_records: 40000
  all_records: False
  output_size: 4
